apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronojob
spec:
  schedule: "*/1 * * * *" # Cada minuto
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure  