apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
        - name: mi-app
          image: mi-nginx-pod:v3
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  selector:
    app: mi-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 80

      