apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-blazor
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mi-app-blazor
  template:
    metadata:
      labels:
        app: mi-app-blazor
    spec:
      containers:
        - name: mi-app-blazor
          image: miblazor:dev
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-service-blazor
spec:
  selector:
    app: mi-app-blazor
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 80
      

# crear aplicacion de .net (Blazor, WebAPI, MVC, etc.)
# crear imagen docker
# crear un deployment con 5 replicas 
# crear un service de tipo LoadBalancer
# probar el acceder desde el navegador a la ip del loadbalancer y al puerto 80xx
      